config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  resources :friend_ships

  resources :friend_requests

  devise_for :users
  get 'users/search',to: "users#search", as: :search
  get 'users/show'

  resources :posts do
    resources :comments
  end






  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_all_friends.html.erb
<% friends.each do |friend| %>
  <%= friend.username %><br/>
<% end %>

app/views/partials/_comment.html.erb
<%= form_with(model: [ post, post.comments.build ],
              local: true) do |form| %>

  <div class="form-group">
    <%= form.label :body %><br>
    <%= form.text_area :body, class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Create Comments", class:'btn btn-success'%>
  </div>

<% end %>

app/views/partials/_show_comment.html.erb
<h4>Comments</h4>
<% comments.each do |comment|%>

  <div class="form-group">
     <%= comment.body%>
  </div>

  <div class="form-group">
    <strong>Comment By:</strong>
    <%= comment.user.username %>
  </div>

<% end %>

app/views/partials/_show_friend_requests.html.erb
<% friend_requests.each do |request| %>
  <%= request.sender.username %><br/>
  <%#= link_to 'Accept', {controller: "friend_requests", action: "update", friend_request: { sender_id: request.sender_id, status_id: 'accepted'}}, method: 'put'%>
  <%#= link_to 'Reject', {controller: "friend_requests", action: "update", friend_request: { sender_id: request.sender_id, status_id: 'rejected'}}, method: 'put'%>

  <%= link_to 'Accept', friend_request_path(request.sender_id,status_id:"accepted"), method: 'put'%>
  <%= link_to 'Reject', friend_request_path(request.sender_id,status_id: "rejected"), method: 'put'%>
<% end %>

app/views/partials/_show_post.html.erb
<%posts.each do |post|%>

  <div class="form-group">
    <strong>Post By:</strong>
    <%= post.user.username %>
  </div>

  <div class="form-group">
    <strong>Title:</strong>
    <%= post.title %>
  </div>

  <div class="form-group">
    <strong>Text:</strong>
    <%= post.text %>
  </div>

  <%= render partial: 'partials/show_comment',locals: {comments: post.comments} %>
  <%= render partial: 'partials/comment', locals: {post: post} %>
  <%= link_to 'Edit', edit_post_path(post) %> |
  <%= link_to 'Back', {controller: "users", action: "show"} %> |
  <%= link_to 'New Post', new_post_path %>

<% end %>

app/views/partials/_show_sent_requests.html.erb
<% sent_requests.each do |sent_request| %>
  <%= sent_request.receiver.username %><br/>
<% end %>