config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  resources :friend_ships

  resources :friend_requests

  devise_for :users
  get 'users/search',to: "users#search", as: :search
  get 'users/show'

  resources :posts do
    resources :comments
  end






  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user, foreign_key: :sender_id
  belongs_to :sender, class_name: "User",foreign_key: :sender_id
  belongs_to :receiver, class_name: "User",foreign_key: :receiver_id
  enum status_id: [:pending, :accepted, :rejected]

  after_update :friend_ship_create

  def self.pending_requests(current_user)
    FriendRequest.where(receiver_id: current_user.id, status_id: 'pending')
  end

  def friend_ship_create
    if self.status_id == "accepted"
      FriendShip.transaction do
        FriendShip.create!(user_id: self.receiver_id, friend_id: self.sender_id )
        FriendShip.create!(user_id: self.sender_id, friend_id: self.receiver_id )
      end
    end
  end

  def self.sent_requests(current_user)
    FriendRequest.where(sender_id: current_user.id)
  end



end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :set_friend_request, only: [:show, :edit, :destroy]

  # GET /friend_requests
  # GET /friend_requests.json
  def index
    @friend_requests = FriendRequest.all
  end

  # GET /friend_requests/1
  # GET /friend_requests/1.json
  def show
  end

  # GET /friend_requests/new
  def new
    @friend_request = FriendRequest.new
  end

  # GET /friend_requests/1/edit
  def edit
  end

  # POST /friend_requests
  # POST /friend_requests.json
  def create
    if current_user.friends.exists?(params[:friend_request][:receiver_id])
      redirect_to users_show_path(current_user), flash: {notice: "You are already friend"}
    else
      @friend_request = FriendRequest.new(friend_request_params.merge(sender_id: current_user.id))
      respond_to do |format|
        if @friend_request.save
          format.html { redirect_to @friend_request, notice: 'Friend request was successfully created.' }
          format.json { render :show, status: :created, location: @friend_request }
        else
          format.html { render :new }
          format.json { render json: @friend_request.errors, status: :unprocessable_entity }
        end
      end

    end


  end

  # PATCH/PUT /friend_requests/1
  # PATCH/PUT /friend_requests/1.json
  def update
    @friend_request = FriendRequest.where(receiver_id: current_user.id,sender_id: params[:id]).last

    if @friend_request.update(:status_id => params[:status_id])
      flash[:notice] = "FriendRequest has been #{params[:status_id]}."
    end
    redirect_to users_show_path(current_user)
  end

  # DELETE /friend_requests/1
  # DELETE /friend_requests/1.json
  def destroy
    @friend_request.destroy
    respond_to do |format|
      format.html { redirect_to friend_requests_url, notice: 'Friend request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend_request
      @friend_request = FriendRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_request_params
      params.require(:friend_request).permit(:sender_id, :receiver_id, :status_id)
    end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_form.html.erb
<%= form_with(model: friend_request, local: true) do |form| %>
  <% if friend_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend_request.errors.count, "error") %> prohibited this friend_request from being saved:</h2>

      <ul>
      <% friend_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sender_id %>
    <%= form.number_field :sender_id, id: :friend_request_sender_id %>
  </div>

  <div class="field">
    <%= form.label :receiver_id %>
    <%= form.number_field :receiver_id, id: :friend_request_receiver_id %>
  </div>

  <div class="field">
    <%= form.label :status_id %>
    <%= form.number_field :status_id, id: :friend_request_status_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friend_requests/edit.html.erb
<h1>Editing Friend Request</h1>

<%= render 'form', friend_request: @friend_request %>

<%= link_to 'Show', @friend_request %> |
<%= link_to 'Back', friend_requests_path %>

app/views/friend_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friend Requests</h1>

<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Receiver</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friend_requests.each do |friend_request| %>
      <tr>
        <td><%= friend_request.sender_id %></td>
        <td><%= friend_request.receiver_id %></td>
        <td><%= friend_request.status_id %></td>
        <td><%= link_to 'Show', friend_request %></td>
        <td><%= link_to 'Edit', edit_friend_request_path(friend_request) %></td>
        <td><%= link_to 'Destroy', friend_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend Request', new_friend_request_path %>

app/views/friend_requests/new.html.erb
<h1>New Friend Request</h1>

<%= render 'form', friend_request: @friend_request %>

<%= link_to 'Back', friend_requests_path %>

app/views/friend_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @friend_request.sender_id %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @friend_request.receiver_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @friend_request.status_id %>
</p>


<%= link_to 'User Profile', {controller: "users", action: "show"} %>