config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  resources :friend_ships

  resources :friend_requests

  devise_for :users
  get 'users/search',to: "users#search", as: :search
  get 'users/show'

  resources :posts do
    resources :comments
  end






  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/friend_ship.rb
class FriendShip < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User',foreign_key: :friend_id
end

app/controllers/friend_ships_controller.rb
class FriendShipsController < ApplicationController
  before_action :set_friend_ship, only: [:show, :edit, :update, :destroy]

  # GET /friend_ships
  # GET /friend_ships.json
  def index
    @friend_ships = FriendShip.all
  end

  # GET /friend_ships/1
  # GET /friend_ships/1.json
  def show
  end

  # GET /friend_ships/new
  def new
    @friend_ship = FriendShip.new
  end

  # GET /friend_ships/1/edit
  def edit
  end

  # POST /friend_ships
  # POST /friend_ships.json
  def create
    @friend_ship = FriendShip.new(friend_ship_params)

    respond_to do |format|
      if @friend_ship.save
        format.html { redirect_to @friend_ship, notice: 'Friend ship was successfully created.' }
        format.json { render :show, status: :created, location: @friend_ship }
      else
        format.html { render :new }
        format.json { render json: @friend_ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friend_ships/1
  # PATCH/PUT /friend_ships/1.json
  def update
    respond_to do |format|
      if @friend_ship.update(friend_ship_params)
        format.html { redirect_to @friend_ship, notice: 'Friend ship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend_ship }
      else
        format.html { render :edit }
        format.json { render json: @friend_ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friend_ships/1
  # DELETE /friend_ships/1.json
  def destroy
    @friend_ship.destroy
    respond_to do |format|
      format.html { redirect_to friend_ships_url, notice: 'Friend ship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend_ship
      @friend_ship = FriendShip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_ship_params
      params.require(:friend_ship).permit(:user_id, :friend_id)
    end
end

app/helpers/friend_ships_helper.rb
module FriendShipsHelper
end

app/views/friend_ships/_form.html.erb
<%= form_with(model: friend_ship, local: true) do |form| %>
  <% if friend_ship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend_ship.errors.count, "error") %> prohibited this friend_ship from being saved:</h2>

      <ul>
      <% friend_ship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :friend_ship_user_id %>
  </div>

  <div class="field">
    <%= form.label :friend_id %>
    <%= form.number_field :friend_id, id: :friend_ship_friend_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friend_ships/edit.html.erb
<h1>Editing Friend Ship</h1>

<%= render 'form', friend_ship: @friend_ship %>

<%= link_to 'Show', @friend_ship %> |
<%= link_to 'Back', friend_ships_path %>

app/views/friend_ships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friend Ships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friend_ships.each do |friend_ship| %>
      <tr>
        <td><%= friend_ship.user_id %></td>
        <td><%= friend_ship.friend_id %></td>
        <td><%= link_to 'Show', friend_ship %></td>
        <td><%= link_to 'Edit', edit_friend_ship_path(friend_ship) %></td>
        <td><%= link_to 'Destroy', friend_ship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend Ship', new_friend_ship_path %>

app/views/friend_ships/new.html.erb
<h1>New Friend Ship</h1>

<%= render 'form', friend_ship: @friend_ship %>

<%= link_to 'Back', friend_ships_path %>

app/views/friend_ships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friend_ship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friend_ship.friend_id %>
</p>

<%= link_to 'Edit', edit_friend_ship_path(@friend_ship) %> |
<%= link_to 'Back', friend_ships_path %>